### ISSUE TITLE
Auto close a tab if title matches regex

### ISSUE THREAD

**Issue by leodoi3** [tabwrangler/tabwrangler#351] opened 2021-09-29 00:56 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to auto-close/refresh a tab if the title matches a regex. Ideally a port from[ this Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/tabautocloseandrefresh/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search). 

**Describe alternatives you've considered**
There aren't any

**Comment by sbipl** [comment] 2021-11-27 04:40
I am Thankful to you on this Beautiful Extension.

I have the same Requirement the modification is that my Page opens in PopUP Chrome New Window and Not Tab, which is not closed by this Extension. 

It will be very Helpful for Us. Thanks

**Comment by ssorallen** [comment] 2021-12-03 14:34
Thank you for this, I am going to close this as a duplicate of #321. You can track the progress there.

**Closed by ssorallen** 2021-12-03 14:34 UTC
