### ISSUE TITLE
Not Closing Tabs

### ISSUE THREAD

**Issue by bschneider15** [tabwrangler/tabwrangler#474] opened 2024-06-07 20:06 UTC
**Describe the bug**
The extension just isn't working anymore

**To Reproduce**

**Expected behavior**
I expect it to work as advertised. It use to work great
**Version (please complete the following information):**

- OS: Windows 11
- Chrome
- Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by ssorallen** [comment] 2024-06-08 14:15
* How many tabs do you have open?
* What are your settings for closing tabs? (see screenshot)
    <img width="481" alt="Screenshot 2024-06-08 at 9 12 53 AM" src="https://github.com/tabwrangler/tabwrangler/assets/29612/cccde315-2ad1-4fbd-9338-bc6a608145b3">
* Please paste logs from Tab Wrangler
  1. Go to "Window" > "Extensions" in Chrome
  2. Toggle "Developer Mode" in upper right
  3. Click the "service worker" link next to Tab Wrangler
  4. Paste what is in the "Console" tab of the debugger

**Comment by ssorallen** [comment] 2024-06-08 16:11
From @TheIndieArmy in discussion #471:

> Even on this version I still have issue where tabs will auto-unlock themselves. Still seems to only be occurring when system RAM usage is high (~95%).
> 
> Not sure if there is anything helpful in this log (no errors were present).
> 
> [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 159.437s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 34.985s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 99.997s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593688
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 35.004s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.015s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 6.464s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 71.474s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593688
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 136.482s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 26.548s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 91.56s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593441
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592441
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 156.564s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 35.005s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593720
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593688
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.011s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 35.003s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.007s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 35.007s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.015s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 11.608s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593731
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593728
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 76.619s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 141.628s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 23.59s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593741
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 88.592s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593740
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593728
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025592355
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 153.603s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 35.004s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.02s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593441
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 34.995s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593728
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593749
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593438
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 99.999s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 34.996s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.002s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593770
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593773
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593776
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 34.999s ago
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593782
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593779
> background.entry.js:1035 [onNewTab] updating new tab Object
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593779
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 100.013s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593784
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593779
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593784
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 21.755s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593779
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 86.764s ago
> background.entry.js:1798 [lostEventsWatchdog]: last alarm 151.772s ago
> background.entry.js:1521 [menus] Updating context menu for tab ID 2025593784

**Comment by ssorallen** [comment] 2024-06-08 16:12
>  Still seems to only be occurring when system RAM usage is high (~95%).

I am going to investigate tabs getting discarded. I did attempt to address tab discarding, which happens with memory pressure, but perhaps I did not correctly cover all cases.

**Comment by bschneider15** [comment] 2024-06-08 20:00
There’s nothing there.


[The Schneider Group]
[https://cdn.gifo.wisestamp.com/im/sh/aHR0cHM6Ly9kNGQ4eGQyMGVyOGxnLmNsb3VkZnJvbnQubmV0L2ZlNGYzZTRlLWI2NzYtNGY5Yi1iYjFhLTNjNDBiZmY0MWZhYi9Ka0tTZ1BpcW1uNXY1aHFKUHZ5YzhEaU02NVRtUmdDUS5wbmcjbG9nbw==/rounded.png]

Bruce Schneider
Residential Specialist | Advisor | Mentor
The Schneider Group | Urban Nest Realty

m. 702.410.6573<tel:702.410.6573>
e.  ***@***.******@***.***>
w. www.theschneidergrp.com<http://www.theschneidergrp.com>
a.  9580 W. Sahara Ave Suite #200

[App Banner Image]<https://theschneidergrp.com/?utm_campaign=signature&utm_source=WiseStamp&utm_medium=email>

**Comment by janwirth** [comment] 2024-06-13 09:12
My tabs are also not closed reliably. I am stuck with 15 open tabs now - and I think the problem is that it's closing only after >20 open tabs.

<img width="722" alt="image" src="https://github.com/tabwrangler/tabwrangler/assets/7485959/42738d90-707d-4023-8068-ef4082f122dc">

**Comment by ssorallen** [comment] 2024-06-13 18:38
@bschneider15 Could you screenshot your settings?

@janwirth Apologies for settings that may have been lost, I tried to ensure that would not happen. If you have 15 tabs open then nothing will get closed - you need to reduce that "20" to the max tabs you want to keep open.

**Comment by bschneider15** [comment] 2024-07-15 17:17
![Screenshot 2024-07-15 101505](https://github.com/user-attachments/assets/aec6fba2-038d-408d-a798-7c8652095bd4)

**Comment by bschneider15** [comment] 2024-07-15 17:18
The extension closed some tabs five days ago, and it was three weeks before that.

**Comment by bschneider15** [comment] 2024-07-15 17:19
![Screenshot 2024-07-15 101857](https://github.com/user-attachments/assets/dd70c95a-5321-418d-a48d-6eee02c84fe8)

**Comment by bschneider15** [comment] 2024-07-15 17:23
I think I found the problem. My minimum was 20 tabs. I changed it to 5. I'll let you know what happens.

**Comment by janwirth** [comment] 2024-08-12 07:38
I think the setting of 5 just got changed to 20 between updates. 5 was perfect.

**Comment by ssorallen** [comment] 2024-08-21 14:10
There were reports from other users that 5 tabs was too few - I was attempting to strike a balance for all users, and the defaults will not suit everyone. Please adjust as you like.

I am closing this because it sounds like everything is working as intended.

**Closed by ssorallen** 2024-08-21 14:10 UTC
Labels: bug

**Comment by janwirth** [comment] 2024-08-22 09:37
I do agree, I think that the change could have been made obvious to the user 'hey, we are changing the defaults' or sth like that. Could have saved everyone some time, including you - so you can do more awesome stuff :)

**Comment by ssorallen** [comment] 2024-08-22 14:56
@janwirth Agreed. The first install UX could be improved as well so folks understand how to adjust to their preferences. As a side project I haven't focused on that though - always open to contributions.
