### ISSUE TITLE
Small popin on vivaldi (chrome based)

### ISSUE THREAD

**Issue by charlesgael** [tabwrangler/tabwrangler#337] opened 2021-06-01 13:21 UTC
**Describe the bug**
When using the plugin on vivaldi, the window is really small (and unusable)

**To Reproduce**
Install on vivaldi, click on the button, voila.

![image](https://user-images.githubusercontent.com/4885210/120330303-fa291980-c2ec-11eb-9c28-874a00eff860.png)

**Expected behavior**
Poping showing normally and providing extension options

**Version (please complete the following information):**
 - OS: Linux
 - Browser Vivaldi
 - Version 3.8.2259.42

**Comment by kronolynx** [comment] 2021-07-07 11:42
I'm having the same problem.

**Comment by timor** [comment] 2021-07-16 12:57
I can confirm this with Vivaldi 3.1.1929.45.

**Comment by ssorallen** [comment] 2021-07-28 14:47
Okay I am unfamiliar with Vivaldi and do not target that browser for Tab Wrangler. I'd be happy to get some help on this if anyone is able to test on Vivaldi.

**Comment by timor** [comment] 2021-07-29 20:01
> Okay I am unfamiliar with Vivaldi and do not target that browser for Tab Wrangler. I'd be happy to get some help on this if anyone is able to test on Vivaldi.

What would testing that involve?

**Comment by KTamas** [comment] 2021-12-11 12:49
as neither of us uses Vivaldi, this is not a priority right now, unfortunately. if someone can investigate it and submit a PR with a fix, that's always welcome.

**Comment by QTaKs** [comment] 2022-08-23 11:55
This appears to be due to the scale setting of the interface: if you return it to 100%, the pop-up window returns to its [normal](https://imgur.com/a/Ou8yn0y) state. 
You can then reduce the scale again and the pop-up window will scale normally.  (First image)
It is also possible to add an extension page to the sidebar as an alternative. (Second image)

**Comment by charlesgael** [comment] 2022-09-17 07:24
Can confirm, nice workaround for this bug, thanks!
Will do the spider tool, more convenient 😁

**Comment by ssorallen** [comment] 2024-05-23 05:46
Closing as "will not fix" since this is not a supported browser. Also sounds like there's potentially a workaround.

**Closed by ssorallen** 2024-05-23 05:46 UTC
Labels: bug
