### ISSUE TITLE
Tabs after session restore do not start their counter

### ISSUE THREAD

**Issue by Sanqui** [tabwrangler/tabwrangler#443] opened 2023-12-05 17:32 UTC
**Describe the bug**
After Firefox crashes or is otherwise restarted and the previous session is restored, tabs that were previously open do not tick down until focus is put on them once.  I suspect this may be a regression.  As a result of this issue, my sessions easily accumulate 100+ tabs which I have to close manually, defeating the purpose of Tab Wrangler.

**To Reproduce**
1. Open a number of tabs in browser
2. Restart the browser
3. The restored tabs display "..." under the Tab lock tab and do not close after any time

**Expected behavior**
The counter for the tabs starts ticking down for all tabs as soon as they are restored.

**Version (please complete the following information):**
 - OS: Fedora Linux 39
 - Browser: Firefox
 - Version: 120.0

**Comment by ssorallen** [comment] 2023-12-05 19:54
@Sanqui Thanks for the issue, I will take a look at this. It does sound like a regression.

**Comment by ssorallen** [comment] 2023-12-09 16:13
I am not able to reproduce this. Is this still happening for you?

This may have been caused by an error when running [the migration added in v7.2.2](https://github.com/tabwrangler/tabwrangler/commit/7276b036efd93fbe6f0c104601c74463c005f029). I will add a timeout to the migration to ensure it gives up the lock so this does not happen for anyone else.

**Comment by Sanqui** [comment] 2023-12-09 22:29
![image](https://github.com/tabwrangler/tabwrangler/assets/289437/93387215-dd09-4d87-b66c-1fcaf6cdff57)

Unfortunately, this is still happening.  Note how most of the tabs show "...", and only after I put focus on the tab it starts counting down.

Any info I could send your way to help debug this?

**Comment by ssorallen** [comment] 2023-12-12 21:37
I found the likely reason for this error, I am pushing v7.2.3. The fix is in commit https://github.com/tabwrangler/tabwrangler/commit/03b766daaf464ba140161a4d56a84b4f56ddf140.

**Comment by ssorallen** [comment] 2023-12-12 21:48
Closing this as fixed in v7.2.3. Please upgrade to the latest version and let me know if you still have issues, and thank you again for reporting.

**Closed by ssorallen** 2023-12-12 21:48 UTC
Labels: bug

**Comment by Sanqui** [comment] 2023-12-17 19:50
I'm on Tab Wrangler 7.2.3 and I have restarted Firefox today.  This issue unfortunately still doesn't appear to be resolved for me...

**Comment by ssorallen** [comment] 2023-12-17 21:37
How many tabs do you have open?

What is the minimum number of tabs you have configured?

If you have fewer than the minimum number of tabs open then the countdown will not progress. Only when you have excess tabs open will you see the countdown happen. Also, the "X tabs" setting is _per window_ not total tabs open in Firefox.

**Comment by Sanqui** [comment] 2023-12-18 09:56
According to Tab Counter Plus, I have over 86 tabs across three windows.  While a significant number of them is pinned tabs, that shouldn't be a problem because I have minimum tabs in Tab Wrangler set to 1:

![image](https://github.com/tabwrangler/tabwrangler/assets/289437/7e56d346-6e48-4b34-a9b3-f2b8f12151b8)


Nevertheless, tabs that are unloaded on browser start still don't come with a timer until I open them, which I demonstrate with this Reddit tab I just clicked on:

![image](https://github.com/tabwrangler/tabwrangler/assets/289437/bcaf9bb0-9eaa-4349-bf00-4b866f6e4dab)
