### ISSUE TITLE
All timers automatically resets after 5 seconds into countdown (kiwi browser) 

### ISSUE THREAD

**Issue by dawn0us** [tabwrangler/tabwrangler#412] opened 2023-06-04 17:16 UTC
**Describe the bug**
All timers automatically resets after 5 seconds in and no tabs are closed as a result. 

**To Reproduce**
1. Open tab wrangler extension page. 
2. Set timer to 10 seconds and min tab to 5 in options page. 
3. Go to "tab lock" page to observe timers of all unlocked tabs (more than 5).
4. All timers share the same countdown. When countdown turns to 0:06, it automatically reverts to 0:10. (Sometimes it's between 0:05 and 0:09.)
5. All tabs remain open. 

**Expected behavior**
Countdown of timers drops to 0:00 and corresponding tabs are closed. 

**Version (please complete the following information):**
 - OS: android 
 - Browser: kiwi
 - Version: v6.9.0

**Reference case**
If timer is set below 5 seconds, timer will countdown to 0 and tabs will be closed as expected. 

**Reference extension**
https://chrome.google.com/webstore/detail/tab-keeper/opphlpkpklmjbglpifmecilchaknobgn
Although not consistently, timers in tab keeper can countdown to 0. Since it's adapted from the same original source, I thought it'd be worth mentioning.

**Comment by clintfred** [comment] 2024-02-06 20:11
I recently started seeing the same behavior on Firefox 122.0 (64-bit) - Linux. I set the time to 1 minute, the timer on all tabs count down to about 0:55, then it is reset to 1:01.

This is a recent behavior change.

**Comment by jacobflanagan** [comment] 2024-02-09 23:42
I'm also experiencing this behavior, using Firefox 115.7.0esr (64-bit) on Debian. I'll add that it seems to only happen while the browser instance is focused (so a separate window of the browser will continue to countdown while not in focus). 

Anyone have an idea what could cause the timer to restart outside of switching to a tab?

**Comment by ssorallen** [comment] 2024-02-10 14:46
Hi, developer here. The timers will reset every 5s if you have fewer than your minimum number of tabs open (this is entirely unapparent, the UI should make that obvious). The minimum number of tabs setting is currently _per browser window_, a feature I have begun to change but have not finished.

**Comment by ssorallen** [comment] 2024-02-13 23:50
@jacobflanagan No no, you are definitely not dumb. Tab Wrangler has many crummy bits like that, the fault lies in Tab Wrangler's UX and poor feature descriptions.

This has been a side project of mine for a number of years, and there is always more to do. Always happy to accept pull requests from folks. Suggestions and bugs are helpful as well, but my desire to work on them comes and goes since this is only a hobby for me.

**Comment by ssorallen** [comment] 2024-12-29 22:45
Closing - feature is working as intended, there were fewer than minimum number of tabs open.

**Closed by ssorallen** 2024-12-29 22:45 UTC

**Comment by pepepaez** [comment] 2025-06-26 18:34
Hi @ssorallen 

I am using Orion Browser on MacOS and this behavior persists even when the number of tabs is above the minimum number of tabs open.

Happy to provide any details that could help diagnose the issue. I don't think this is a bug per se because it works fine in Chrome but given that I mainly use Orion (because Safari does not support extensions) I would like to see if there's a way to identify a way to make it work here.

Thanks for your work, this extension would give me just everything I need to be able to use Orion more efficiently.
