### ISSUE TITLE
Timer keeps resetting itself after 5 seconds in unlocked tabs

### ISSUE THREAD

**Issue by ItsDanielHarris** [tabwrangler/tabwrangler#142] opened 2017-07-13 19:42 UTC
I have the timer set to 2 minutes and when it counts down to 1:56-1:55 mark, it resets. It does it in a non-stop loop. This happens in Chromium 56 in Raspbian Jessie.

**Comment by ssorallen** [comment] 2017-07-13 20:06
How many tabs do you have open? The timer resets if you have fewer than the minimum number of tabs open so that when you finally open a new tab it doesn't immediately close other tabs.

**Comment by TheWebAuthor** [comment] 2017-07-13 20:12
One pinned tab and one unlocked tab. It worked the first time, and when I re-opened the same unlocked tab, the problem happened.

**Comment by ssorallen** [comment] 2017-07-13 20:53
What are your settings? What's the minimum number of tabs you want open?

**Comment by TheWebAuthor** [comment] 2017-07-19 18:54
Close inactive tabs after: 1 minute
Don't auto-close if I only have: 30 tabs open
Remember up to: 10 closed tabs
Checked - Clear closed tabs list on quit
Unchecked - Show # of closed tabs in url bar

I need all the tabs closed after 1 minute except for the 1 pinned tab.

**Comment by ssorallen** [comment] 2017-07-20 07:15
> Don't auto-close if I only have: 30 tabs open

Change that to 0.

Pinned tabs are never closed automatically, so no need to worry about that one.

**Comment by TheWebAuthor** [comment] 2017-07-25 15:11
Changed it

**Comment by TheWebAuthor** [comment] 2017-08-01 13:53
Bump

**Comment by brandondees** [comment] 2017-10-26 22:16
I'm seeing this issue also. no tabs have been closed, even after tweaking the configuration to various values. the clock is resetting every few seconds

**Comment by brandondees** [comment] 2017-10-27 22:06
I just realized the "don't auto close if i only have N tabs" setting is a per-window count, not global, so if it's set to 10, only windows with greater than 10 tabs open will have any tabs closed. 

I think this issue can be addressed adequately by clarifying the expectation in the UI copy:

![image](https://user-images.githubusercontent.com/185732/32126944-16bf284c-bb39-11e7-871f-974c1673fe3d.png)

change to "tabs open in a single window"

**Comment by KTamas** [comment] 2021-12-11 12:10
This is probably easy to fix. PRs welcome.

**Comment by ssorallen** [comment] 2021-12-11 20:57
Related to https://github.com/tabwrangler/tabwrangler/issues/95. The "per window" feature is not apparent nor is it configurable.

**Comment by ssorallen** [comment] 2023-12-13 14:37
Closing as a duplicate of #95 since the issue is related to the poor description of the per-window behavior. Exposing per-window functionality in #95 and describing how it works covers this issue as well.

**Closed by ssorallen** 2023-12-13 14:37 UTC
Labels: bug
