### ISSUE TITLE
Timer keeps reseting after restart and therefore tabs actually never close.

### ISSUE THREAD

**Issue by gishfishlx** [tabwrangler/tabwrangler#339] opened 2021-06-14 15:04 UTC
Timer keeps reseting after restarting my computer and therefore tabs actually never close.
Updating Firefox without computer restart does also reset the timer.

Firefox latests version is used.
I have more than 2200 tabs open (yea don't ask)
I set timer to 10 days/14400 minutes (i need it that way please don't ask either)

Is this a bug or a feature? Is tab wrangler meant to save timer accross sessions?

thanks

**Comment by Vondor** [comment] 2022-04-26 10:19
Yes, I am also having that "Problem". I only have 250 Tabs and need them for two weeks, but same.
Would be nice if tabwrangler would just save the time for the tabs when firefox gets closed.

Thanks!

PS.: Also, didnt found any other solution for that. But every mobile browser has this as an build in feature without plugins.

**Comment by ssorallen** [comment] 2022-12-25 14:23
Closing as a duplicate of https://github.com/tabwrangler/tabwrangler/issues/130. This is the next issue I am fixing.

**Closed by ssorallen** 2022-12-25 14:23 UTC
Labels: duplicate
