### ISSUE TITLE
Track inactivity time only when browser is actively being used.

### ISSUE THREAD

**Issue by oleg-slapdash** [tabwrangler/tabwrangler#361] opened 2022-01-10 02:20 UTC
**Is your feature request related to a problem? Please describe.**
I have two use cases:
- I opened a bunch of tabs on Friday evening. I come Monday morning and all tabs are closed since they timed out over the weekend.
- I opened a bunch of tabs and then spent the whole day in meetings. In the evening all tabs are gone.

**Describe the solution you'd like**
There are two reasons why I use this extension: reduce the overhead of running a bunch of tabs AND focus my work on important things and if the tab is not visited it is probably not important. I'd like to have a combined limit on the number of tabs open and on the time since they've been used. For example: For the N most recent used tabs, close them after A minutes. For all other tabs, close them after B minutes. Where N, A, B are configurable. Bonus points for only tracking time when the browser is actively being used.

**Describe alternatives you've considered**
- Don't track time on the weekends - not really universal and everyone has different weekends.
- Track time when the computer is active (easily done with setInterval since the event loop will be stalled when the computer is asleep).

**Comment by DasCanard** [comment] 2022-09-04 16:49
I personally prefer that the time is also counted as long as the browser is not active. The whole thing is quite good for gamers because you often forget to close tabs and, as you know, they draw a lot of resources.

Nevertheless, the whole thing might be convertible as a setting.

**Comment by hlmaldon** [comment] 2023-08-03 13:17
But in my case, the last tab does not close, any recommendations?
I set it up like you suggest it.

"For example: I have the countdown set to 25 minutes and the "Automatically close tabs if more than" set to 0.
In this case, the whole thing goes so far that any tabs are closed until the browser is closed."

**Comment by ssorallen** [comment] 2024-04-22 15:56
This has been a desired feature since the very beginning. I am always open to pull requests for new features! I am going to close this as a duplicate of #5 and consolidate discussion there.

**Closed by ssorallen** 2024-04-22 15:56 UTC
