### ISSUE TITLE
tabs just disappearing in Tab Corral?

### ISSUE THREAD

**Issue by goldjerry1** [tabwrangler/tabwrangler#214] opened 2018-03-08 22:12 UTC
Once I got to 100, I went into Tab Corral to clear out old tabs.  What I found was the same 2 or 3 tabs, repeating over and over again.  Instead of what should have been there which was a bunch of important tabs I didn't want to lose.

Any idea how this happened? how I can retrieve the old ones? how to prevent it happening again?

thanks.

**Comment by ssorallen** [comment] 2018-03-14 11:02
Which version of Tab Wrangler are you using? You can go to *Options* to see the version number. The issue you're seeing sounds similar to #172, which was fixed in [v5.6.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.6.0).

**Comment by goldjerry1** [comment] 2018-03-16 00:02
it's 5.11.  Just happened again, see screenshot.  I have 200 lines of the same three tabs.

![screen shot 2018-03-15 at 8 00 49 pm](https://user-images.githubusercontent.com/37195663/37496918-aef8efde-288b-11e8-8601-c4594c757e81.jpg)

**Comment by ssorallen** [comment] 2018-07-16 13:42
Thank you for the bug report. I am closing this in favor of #234 because I believe it is the same root cause: a bunch of unwanted tabs were added to your list, and they deleted the older desired tabs. Please comment on this bug if you think it's a separate issue or follow #234 for other updates.

**Closed by ssorallen** 2018-07-16 13:42 UTC
Labels: bug, duplicate
