### ISSUE TITLE
Feature Request: Wrangle Only Specific Types of Tabs

### ISSUE THREAD

**Issue by sinatra1830** [tabwrangler/tabwrangler#112] opened 2017-02-18 20:56 UTC
I like leaving tabs open as a sort of long-term to do list. I just hate having a billion facebook tabs to distract me. If you could, please add the functionality only to wrangle tabs with specific URLs. (eg. www.facebook.com).

Thanks!

**Comment by rynowin** [comment] 2017-02-25 18:50
Duplicates https://github.com/jacobSingh/tabwrangler/issues/87

**Comment by ssorallen** [comment] 2017-09-08 17:15
Closing as duplicate of #87.

**Closed by ssorallen** 2017-09-08 17:15 UTC
Labels: duplicate, enhancement
