### ISSUE TITLE
Duplicate tabs appearing in Corral.

### ISSUE THREAD

**Issue by keyoti** [tabwrangler/tabwrangler#172] opened 2017-10-24 16:55 UTC
It seems when I hibernate and come back that I'll get several of my tabs going to the Corral and being duplicated 3 or 4 times in there.  So far I haven't identified any pattern to it.

An example URL that did this: https://support.apple.com/en-ca/HT201593

Wrangler v5.5.0
Chrome 61.0.3163.100

It also will occasionally (not necessarily related to hibernate) put locked tabs in the Corral.  To me this makes me think something is up with the URL comparison code(?).

Great extension by the way, it has freed up a lot of resources on my machine!

**Comment by keyoti** [comment] 2017-11-01 17:19
This morning I had hundreds of duplicate tabs corralled - so I either have to fix this or stop using it.  Can anyone provide any tips on where to look for this problem? Since I don't have time to properly diagnose this, I might just opt to not add more than one copy of a URL to the Corral - if I do that, would you like a PR?

**Comment by ingorichter** [comment] 2017-11-01 22:45
Hm, sorry to hear that you are experiencing this weird behavior.

I've never seen this myself, so I don't know how to force and repro it properly.

As a workaround, you can specify in the **Options** under **Prevent duplicate tabs in the Tabs Corral** to avoid having duplicate URLs in the Corral. I know that this doesn't solve the underlying issue, but it would prevent your Corral from overflowing.

I assume you are on macOS and you close the lid to put your machine into sleep/hibernation? Do you have an external monitor attached to your machine?

**Comment by keyoti** [comment] 2017-11-02 00:28
@ingorichter thanks I have set that property and will see if it rectifies it.  

I'm on Windows 10, desktop, with 2 monitors (often I have a couple of Chrome windows open if that could affect it).

**Comment by ssorallen** [comment] 2017-11-04 09:50
Thank you for reporting this problem.

I have a hunch about what's causing it: `setInterval` queueing multiple times while the computer is hibernating and synchronously running the tab closing code multiple times. `chrome.tabs.remove`, like most of the Chrome Extension API, is asynchronous so each call of the tab closing function still sees the same list of tabs that the previous call did if the calls are done in quick enough succession.

A fix would be to replace `setInterval` with `setTimeout` and queue the next call of the tab closing code only at the end of the function passed to `setTimeout`.

I'm having a difficult time reproducing this, and I don't know if that's due to using a different operating system or that Chrome behaves differently on Mac vs. Windows, but this does seem like the culprit.

**Comment by keyoti** [comment] 2017-11-07 04:41
That seems reasonable – I will need to get setup to develop Chrome extensions and will try out what you suggest.

**Comment by ssorallen** [comment] 2017-11-07 05:34
I am also happy to ship a change that might fix this. The functionality will be exactly the same for the extension, but it might eliminate this issue.

@keyoti It’d be helpful if you were able to able to come up with a way to reproduce this on your machine so when I ship the new version you can confirm whether the issue is gone. I’d greatly appreciate any help. I was trying something like the following:

1. Create a new Chrome Profile and install Tab Wrangler for it
2. Change settings to a small close time, like 1min, a small number of minimum tabs, like 1
3. Open a bunch of tabs and note how many you open, like 10
4. Force your computer to hibernate 
5. Wait some multiple of the minimum close time, like 5 minutes
6. Wake your computer up
7. See if Tab Wrangler ends up with duplicate tabs

I use a separate Chrome Profile for testing Tab Wrangler so I’m not worried about it interfering with my real daily usage.

**Comment by ssorallen** [comment] 2017-11-11 06:03
> I had 8 tabs open when I hibernated, on wakeup it correctly took 3 away but there are 96 in the corral, so it seems to have duplicated them 32 times, over a (roughly) 9 hour period.

That's a lot of duplicates. Thanks for reproducing it. I will work on a potential fix and let you know when I ship it.

**Closed** 2017-12-11 09:13 UTC

**Comment by ssorallen** [comment] 2017-12-12 15:04
[v5.6.0](https://github.com/tabwrangler/tabwrangler/releases/tag/v5.6.0) contains my potential fix for this bug. @keyoti once your version updates to ^5.6.0, I'd appreciate any testing you might be able to do. I hope this solves your issue and makes the extension usable for you.

**Comment by keyoti** [comment] 2017-12-18 16:46
Thanks @ssorallen - it seems to be fixed now!

**Comment by ssorallen** [comment] 2017-12-18 19:45
@keyoti Excellent. Let me know if you have any other problems. Thanks for the help in tracking down and testing this issue.
