### ISSUE TITLE
Locked tabs are lost when browser restarts

### ISSUE THREAD

**Issue by AsteriskSteve** [tabwrangler/tabwrangler#396] opened 2022-11-30 09:07 UTC
Edge Version 107.0.1418.56 (Official build) (64-bit)

After restarting Edge, the locked tabs selection is not preserved.
Everything else seems to work fine.

**Comment by ssorallen** [comment] 2022-12-02 20:28
This appears to be for the entire extension, and was intentional for some reason? I'm unsure of the history here, but this line should be modified:

https://github.com/tabwrangler/tabwrangler/blob/master/app/background.ts#L162

**Comment by ssorallen** [comment] 2022-12-02 20:47
I removed the "MS Edge" prefix in the title because this logic applies to every browser.

**Comment by ssorallen** [comment] 2022-12-19 14:45
Closing as a duplicate of https://github.com/tabwrangler/tabwrangler/issues/130. This will be the next issue I fix.

**Comment by ssorallen** [comment] 2022-12-20 17:00
This is not actually a duplicate of #130; that issue is about the tab timers.

**Closed** 2022-12-20 17:03 UTC
Labels: bug
