### ISSUE TITLE
Timer starts when real see this page.

### ISSUE THREAD

**Issue by BigAN** [tabwrangler/tabwrangler#262] opened 2019-01-12 16:18 UTC
we always open many pages when starts a interest on somthing. but 10 minutes (time to close) is not enought for us to review all pages , so i think the timer starts when we real starts reading that is important for this scene.

**Comment by KTamas** [comment] 2021-12-11 12:26
oh, yeah, this would be very useful and important.

**Comment by ssorallen** [comment] 2024-05-23 04:54
Closing as duplicate of #472.

**Closed by ssorallen** 2024-05-23 04:54 UTC
Labels: enhancement
