### ISSUE TITLE
Remove tabs from list when same URL is opened again

### ISSUE THREAD

**Issue by yogesh-zendrive** [tabwrangler/tabwrangler#217] opened 2018-03-14 20:53 UTC
Steps to reproduce:
- Open https://www.google.com
- Let it be closed by Tab Wrangler
- Open a new tab and open https://www.google.com again
- This does not remove https://www.google.com from the list of closed tabs in Tab Wrangler plugin, I don't want to open a tab that is already open so it's not useful to see that URL in the list of tabs

**Comment by ssorallen** [comment] 2018-03-15 15:43
Thanks for the issue.

Tab Wrangler won't remove google.com from the list in your example, and that is by design. Tab Wrangler's tab list only changes when tabs are closed, not when they are opened. This might be an interesting enhancement though.

**Comment by KTamas** [comment] 2021-12-11 12:18
@yogesh-zendrive this would be an interesting enhancement, but it's not a priority right now. PRs welcome.

**Comment by ssorallen** [comment] 2024-05-23 17:51
Closing as "will not fix." The closed tab list will not be a focus of new features - tabs that Tab Wrangler closes should really be ones you didn't need. Focus for now will be better tools around when/which tabs are closed.

**Closed by ssorallen** 2024-05-23 17:51 UTC
Labels: enhancement
