### ISSUE TITLE
All my tabs are removed!!!

### ISSUE THREAD

**Issue by Shramkoalexander** [tabwrangler/tabwrangler#241] opened 2018-07-27 20:04 UTC
All my tabs have been removed!!! What happened? Help me to restore my tabs, please!!!!

**Comment by CesarHernandezN** [comment] 2018-07-28 23:42
Same happened with me on Chrome, is there any file I could look for?
Thank you in advance

**Comment by ssorallen** [comment] 2018-07-29 03:31
@CesarHernandezN There isn’t a file, but the data might still be in Tan Wrangler’s storage and wasn’t migrated properly. It that is the case, it can be recovered.

Have you tried disabling and re-enabling the extension? (Don’t uninstall it.) Go to Tools > Extensions and click the “Disable” button next to Tab Wrangler and then “Enable”. That might force the migration.

If the re-enabling has no effect, I will add code to recover data if it is still there and correctly migrate it. I will post updates to this issue.

**Comment by ChossHunter** [comment] 2018-07-29 15:31
@ssorallen No dice on disabling and re-enabling. Would like to see a fix for this if possible, had about 30 tabs saved lol.

**Comment by ssorallen** [comment] 2018-07-29 16:12
Okay thank you for testing, @ChossHunter. I almost have a temporary feature working that will check for data in the old location and let you correctly migrate it. 

Sorry again for this. I obviously missed something in my testing even though the migration worked on my Chrome and Firefox.

There won’t be any more data migrations like this, no more chance of data loss.

**Comment by ChossHunter** [comment] 2018-07-29 16:18
No worries @ssorallen these things can happen with any software product. You offer an amazing priduct, for free at that, and you continue to work on it and support it, AND your in community response is present. I can only speak for myself, but im positive I'm not the only one, that appreciates what you're doing, and the effort you put into it. So thank you.

I would offer to debug stuff for you, but it's been well over a decade since I've written any code (C/C++), so I probably wouldn't be of any help there unfortunately, but if you can think of anything you need help/testing with, just let me know...

**Comment by CesarHernandezN** [comment] 2018-07-30 16:35
Hi @ssorallen 
Sadly it did not migrate the data by enabling/disabling, I believe the issue goes related on data restrictions since my company computer ask me for confirmation/permissions when moving data inside particular folders like windows, or C: root for example

**Comment by ssorallen** [comment] 2018-07-31 12:28
@CesarHernandezN Thank you for testing. The data is still inside Chrome, so I don't think disk permissions should affect it.

PR #243 recovers data from the previous location if it still exists. You don't need to do anything, upgrading to the next version, v6.1.0, will automatically recover data if it still remains. I'll keep this open to see if the change helps you all.

**Comment by ingorichter** [comment] 2018-08-01 18:32
Hm, after the 6.1.0 update my data is gone entirely in Chrome. Yesterday I had ~450 tabs and overnight when the update was installed everything is gone. I've inspected the storage areas, and there is nothing left. I have a backup, but after all the other updates when nothing was removed this an unwanted surprise.

**Comment by ChossHunter** [comment] 2018-08-01 20:00
Yeah, so I just checked, I am upgraded to 6.1.0 now, and my missing tabs from version 6.0.0, never came back unfortunately. Any thoughts @ssorallen ?

**Comment by ssorallen** [comment] 2018-08-02 02:03
I apologize, @ingorichter. I just pushed out [v6.1.1](https://github.com/tabwrangler/tabwrangler/releases/tag/v6.1.1) to remove the migration. If it's working inconsistently, then it shouldn't be done at all. If someone had not yet been upgraded to v6.1.0, they'll go straight to v6.1.1 and skip the potential broken migration.

This is frustrating that I can't trust Chrome to work the same everywhere. I don't know what's happening now because each of these releases has worked fine both in testing and when my regular profile that uses the Chrome Webstore version was updated. I have been forcing an update in my regular profile by turning on dev mode and clicking "Update", but if that makes the update behave differently then it's even more frustrating.

**Comment by ChossHunter** [comment] 2018-08-02 02:38
This is what I got to that line of text:

![wrangler](https://user-images.githubusercontent.com/41870441/43559300-6c301c50-95c2-11e8-8d24-396d76e24ee3.jpg)

**Comment by Shramkoalexander** [comment] 2018-08-02 04:29
@ssorallen And this is what I got:
![screenshot_20](https://user-images.githubusercontent.com/24633144/43562527-8c3fe588-9636-11e8-935b-53c08e1e2169.jpg)

**Comment by ssorallen** [comment] 2018-08-02 08:01
@ChossHunter @Shramkoalexander I unfortunately only have bad news given the screenshots you guys shared. It appears as though your pre-v6.0.0 data is gone. As far as I know, there is no way to recover it. Tab Wrangler does not send your data anywhere, it has no tracking of any kind. There is no central backup to recover from.

You can always access your full browsing history in Chrome's own history tool by going to *History > Show Full History*. All tabs you opened will be in there, including those that Tab Wrangler closed.

I realize telling you to use another tool because this tool lost your data is a horrible answer to give, and I regret that it's the best I can give you. I thought I understood what my changes in v6.0.0 would do, and I thought they were safe given my testing. I was obviously wrong, and I apologize for losing your data.

I won't attempt any changes like this again, so your data will not be lost again.

**Comment by CesarHernandezN** [comment] 2018-08-02 13:11
@ssorallen I also got lost my data after confirmed with the command you gave us but don't feel bad, I understand it behaves differently on every computer/region, next time when moving sensitive data, request to do a manual back-up and that solves the issue.
It is a great tool anyway, clear an concise, I appreciate all your effort.

**Comment by SamaevArtem** [comment] 2018-08-02 14:15
Hello.
(I use an interpreter from Russian to English)
I seem to have found my tabs (or some of them).

1) I found the developer console in the screenshots above.
2) I found the name Tab Wrangler on my computer (On the Sources tab - egnjhciaieeiiohknchakcodbpgjnchh).
3) I performed a search on my computer by "egnjhciaieeiiohknchakcodbpgjnchh".
4) Through "Notepad ++" I looked at different files from the found folders and found the file:
C: \ Users \ Artem \ AppData \ Local \ Google \ Chrome \ User Data \ ghifackarapulyfinck \ Local Extension Settings \ egnjhciaieeiiohknchakcodbpgjnchh \ 000288.log
5) In this file there are paths / links to my tabs (I make a search in the file by "http", every second value is a link to my tab)

I do not automatically save tabs in Tab Wrangler.
I saved all of my tabs in the Wrangler Tab using the Key Combination (I have it Ctrl + Shift + T).

Here is an example from the file:
{"active": true, "audible": false, "autoDiscardable": true, "closedAt": 1532519520242.0, "discarded": false, "favIconUrl": "https://s.ytimg.com/yts/img/ favicon_32-vflOogEID.png "," height ": 805," highlighted ": true," id ": 59," incognito ": false," index ": 13," mutedInfo ": {" muted ": false}," pinned ": false," selected ": true," status ":" complete "," title ":" РљР ° Рє РІС <Р ± СЂР ° С,СЊ РјРѕРЅРёС,РЅСЂ? Р'СЃС 'РїСЂРѕ РјР ° С,СЂРёС † С <, СЏСЂРєРѕСЃС,СЊ, РєРѕРЅС,СЂР ° СЃС,РЅРѕСЃС,СЊ Рё РІСЂРјРјСЏ РѕС,РєР »РёРєР °. - YouTube", "url": "https://www.youtube.com/watch?v=zjTbCMWRACA "," width ": 1600," windowId ": 40}

Here is my tired reference:
https://www.youtube.com/watch?v=zjTbCMWRACA
There are many such references.


I hope this helps someone ...

**Comment by Shramkoalexander** [comment] 2018-08-02 14:35
@SamaevArtem Thanks a lot, man. It works, you really helped me out!!! Спасибо, чувак, ты спас меня)))

**Comment by ssorallen** [comment] 2018-08-02 14:41
@SamaevArtem Thank you for that. I did find the same file on MacOS:

    /Users/<username>/Library/Application Support/Google/Chrome/Default/Local Extension Settings/egnjhciaieeiiohknchakcodbpgjnchh/<number>.ldb

After some digging, Chrome stores [Extension data in LDB files](https://stackoverflow.com/a/35142175/368697). I'm not sure how easy it is to extract data from there. @Shramkoalexander, were you able to recover data from the file?

**Comment by SamaevArtem** [comment] 2018-08-02 15:46
This can be done differently, but I used Notepad++.

1) After each link, I put the end-of-line character (Menu "Replace"):
","
Replaced by:
\r\n

2) Delete everything that is in the line before the link (Menu "Replace"):
.*(http.*).*
Replaced by:
$1

3) I mark all the lines with links to the bookmark (Menu "Annotations"):
.*(http.*).*
Mark all. (Worth the daw "Mark Bookmark")

4) Delete all the lines except the links:
Menu: Search -> Bookmarks -> Delete all rows Without Bookmarking

Now there are only links to the logo and to our sites.

(Make a backup file! It seems there is a possibility of deleting links!)

**Comment by Shramkoalexander** [comment] 2018-08-03 07:30
@SamaevArtem Yes, thank you! After that you need to remove all duplicates. There are a lot of duplicates. I had 4000 links and after removing duplicates I have 300. 

The easiest way for me to delete all duplicates was through copying all the links to Excel:

- First of all make sure that all your links were placed on each line (follow the instructions from @SamaevArtem)

- Copy all your links to Excel

- then follow the instructions - https://support.office.com/en-us/article/find-and-remove-duplicates-00e35bea-b46a-4d5d-b28e-66a552dc138d?omkt=en-US&ui=en-US&rs=en-US&ad=US

Also you may remove all the links with "favicon" and ".ico". In Notepad++ I did the following:

- Make sure that all your links were placed on each line ((follow the instructions from @SamaevArtem))

- Use regular expressions  
.\*favicon.\* 
and
.\*\\.ico.\*

- Then mark all the lines:

![default](https://user-images.githubusercontent.com/24633144/43629601-3343c5f8-9717-11e8-8ca8-f545ebea88f3.jpg)

![default](https://user-images.githubusercontent.com/24633144/43629687-66561ad6-9717-11e8-8d3d-69bc329a309e.jpg)

- Then Menu -> Search -> Bookmark -> Remove Bookmarked Lines
 
In the end, you will have all your missing links!

P.S.: Sorry for my English

**Comment by Shramkoalexander** [comment] 2018-08-03 07:44
@ssorallen No, I don't know how to do this differently

**Comment by SamaevArtem** [comment] 2018-08-04 09:00
My tabs are gone again (
![image](https://user-images.githubusercontent.com/42037696/43674510-e6e54688-97dd-11e8-97c5-a2811fee8860.png)

**Comment by ssorallen** [comment] 2018-08-04 10:07
@SamaevArtem Again? What do you mean? Which version did you get upgraded to? v6.1.1 has no data changes.

**Comment by SamaevArtem** [comment] 2018-08-04 11:30
Yes. I added a few tabs yesterday, and today (after rebooting the computer) there are no tabs.

I did not update the program myself.
Tab Wrangler v6.1.1
This version was installed on its own (I did not change the version of Tab Wrangler from the moment it was installed).

**Comment by Shramkoalexander** [comment] 2018-08-06 10:02
Hello, @ssorallen! Something wrong with my TabWrangler again:

I had 9 wrangled tabs and after rebooting my PC, I lost them. The list of wrangled tabs is empty, but icon still indicate about 9 wrangled tabs

![screenshot_24](https://user-images.githubusercontent.com/24633144/43710394-f0cca586-9988-11e8-8c75-6f24c206dc9a.jpg)

**Comment by ssorallen** [comment] 2018-08-06 10:44
@Shramkoalexander 

🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

I'm now debugging the storage library Tab Wrangler is using, [redux-persist](https://github.com/rt2zz/redux-persist), because I can't understand what is happening and still haven't been able to reproduce the problem locally.

Does this happen if you just exit your browser and restart it?

Can you see what data you have in Chrome now? You can run the code like before:

     chrome.storage.local.get(null, data => { console.log(data); })

**Comment by ssorallen** [comment] 2018-08-07 02:17
This unfortunately might be an underlying error in redux-persist, the library that saves and restores data from the Chrome/Firefox local storage: https://github.com/rt2zz/redux-persist/issues/809

I'm investigating further. I am pushing out v6.1.4 to mitigate this issue, but it might require removing redux-persist all together.

**Comment by ssorallen** [comment] 2018-08-07 09:41
I was able to confirm that https://github.com/rt2zz/redux-persist/issues/809 does indeed wipe out storage if they exceed the timeout. The default is 5 seconds, which I could see being passed if you open your browser immediately after booting your computer, if you have a physical disk that takes longer to access, and many other possibilities that would make your computer slow.

Since users unlikely view Tab Wrangler immediately upon launching the browser, I increased the timeout to 60 seconds so there's very little possibility of it being reached: https://github.com/tabwrangler/tabwrangler/commit/7e592afcef97309c8508b50b81ba7973429d068e

This change will mitigate data loss for all users even when the browser storage is very slow to respond.

"Mitigate" is not great, I want to be able to say "eliminate." I will see if what can be done in redux-persist to fully prevent this from happening.

**Comment by Deadser** [comment] 2018-08-09 00:02
I've got the same issue--lost my tab data--twice in the last couple of weeks. I don't think it's the same issue mentioned, as my computer is on all the time, so there hasn't been a reboot. I think it's actually happening after updates, but can't be sure. I lost all of the tabs a couple of weeks ago, and spent a LONG time going through my Chrome history, trying to get them back. Then I just noticed today that they're all gone again. It also seemed to unlock my locked tabs, and has, since I've been typing this, moved them into storage. I'm pretty sure that I exported them last time this happened, so I'm hoping I can get them back that way, although I don't know if that will work.

**Comment by ssorallen** [comment] 2018-08-09 02:48
@Deadser Do you remember when that last happened?

I apologize for that lost data. I've been trying to reproduce this on my computer so I can definitively say I fixed it, but I have yet to run into this problem. I was able to cause data loss by changing some settings in a library that I added and artificially making Chrome slow, and so v6.1.5, which was released 2 days ago, included further changes to prevent that source of data loss.

I've been considering rolling back the changes made from v5 -> v6, but I made them in order to enable a bunch of features that have been requested for a long time.

**Comment by ssorallen** [comment] 2018-08-21 13:49
@Deadser By “slowness” I was thinking of a situation like your computer is waking up from sleep, Chrome is not the foreground window, you have a bunch of other applications open, etc., and Chrome gets much lower priority than other processes. In that situation even a powerful computer could starve Chrome for >5s and potentially hit this issue.

I increased the timeout to 60s, which I believe for all real world cases “fixes” the issue. However, the underlying issue appears to be error handling in a library TW uses called redux-persist. I am watching the issue in case the authors are able to come up with a solution.

**Comment by davask** [comment] 2018-08-21 14:30
`tltr;` twice, I wrangled a bunch of tabs (250 & 42 the second time) in both cases, I ve lost most of them.
Any idea why, is it related to the switch of the save system ?
is there anyway to fix it ? or debug or trace that issue ?

**Comment by ssorallen** [comment] 2018-08-21 14:38
@davask Did that data loss just happen?

**Comment by pravhoven** [comment] 2018-09-29 12:18
Alright so i lost all my tabs. I had 172 wrangled, 3 were pinned and 2 were normal tabs. Then i closed chrome. When i opened it again it automatically opened the pinned ones too. But i wanted the unpinned ones too, so i clicked history and restore "5 tabs" cuz it restores the pinned ones too for some reason.

And then i noticed all the wrangled ones were gone.

Read this thread and tried disabling and enabling the extension, opening and closing chrome. Didnt work.

Then closed chrome and i went to:
AppData\Local\Google\Chrome\User Data\Default\Local Extension Settings\egnjhciaieeiiohknchakcodbpgjnchh

Noticed a (number).log file that had just being created recently and a bunch of (number).lbd with older dates and hours. So looking at the time around when i remember them working fine, i chose one of the .lbd ones and changed it to .log.

Opened chrome again, and now all the tabs are back.

![wrangler](https://user-images.githubusercontent.com/43700682/46245673-5490b000-c3b7-11e8-8f42-53eb0478f39c.png)

Also a lost folder was created

![image](https://user-images.githubusercontent.com/43700682/46245679-7427d880-c3b7-11e8-9327-b57c65a2862f.png)

With just these 2 files.

Everything seems back to normal.

Would appreciate if this didnt happen again. Thanks.

**Comment by ssorallen** [comment] 2018-09-30 04:14
@pravhoven The folder was named “lost”? Was there anything relevant in that .log file?

This may be the same root cause as this thread, but I can’t be certain. When I have time I’d like to debug the core issue, but I haven’t been able to yet. 

Thank you for posting all the info, and apologies for the data loss.

**Comment by pravhoven** [comment] 2018-09-30 17:12
@ssorallen yes thats the name of the folder and it appeared on its own after launching chrome again after changing the file type. and this was in the log file inside "lost", opening it with notepad++

![image](https://user-images.githubusercontent.com/43700682/46260295-b16c9300-c4a9-11e8-979b-efa97085792d.png)

the other files seems to keep counting onwards, and there is always one .ldb ahead of the actual .log.

![image](https://user-images.githubusercontent.com/43700682/46260319-ec6ec680-c4a9-11e8-9b31-d3bcc06787d4.png)

do you want me to look into any other file or open the 159 one inside "lost" with any other program?

**Comment by pravhoven** [comment] 2018-09-30 17:52
also i just noticed that when i recreated the problem i wrote "lbd" instead of "lbd" as file type, that was just me trying to recreate it for the screenshot, the lost folder and everything else happened when i did it correctly before.

![image](https://user-images.githubusercontent.com/43700682/46260750-956bf000-c4af-11e8-8431-257cddb5cd76.png)

**Comment by robinleeuw** [comment] 2018-10-20 06:52
Hi, for me this has happened several times when my battery ran out. 
Situation: battery dies -> I plug it in and restart -> open Opera -> all wrangled tabs are gone. 

I'm using Opera, Tab Wrangler 6.4.0.

**Comment by ssorallen** [comment] 2018-11-11 04:41
I released v6.4.1 today after investigating redux-persist, a 3rd-party library Tab Wrangler is using like I mentioned before. Though v6.4.0 mitigated the issue, v6.4.1 completely disables the broken feature that I confirmed was causing data loss.

Please comment if you still see any issues. I've gone a bit quiet because I have been working more lately, but I'm still interested in Tab Wrangler's development and reliability.

Commit https://github.com/tabwrangler/tabwrangler/commit/4e2f38945a9984a7ae32f97540499e789045a1e8 disables the broken feature in redux-persist.

**Comment by ssorallen** [comment] 2019-03-26 03:07
There have been several minor and patch releases containing fixes to solve this issue. I was able to reliably reproduce one issue and fixed it in v6.4.1, as mentioned in my previous comment.

Because there have been no reports of data loss for several months now, I am going to anecdotally consider this fixed. All users are now upgraded to versions with the best fixes known so far.

If any of you still see issues, please let me know. Thanks for all of the help and patience working through this issue.

**Closed by ssorallen** 2019-03-26 03:07 UTC
Labels: bug
