### ISSUE TITLE
All of the tabs in a window reset their timer together, even when I only access one tab

### ISSUE THREAD

**Issue by project716com** [tabwrangler/tabwrangler#363] opened 2022-01-21 15:28 UTC
**Describe the bug**
All of the tabs in a Chrome window reset their timer together.  Sometimes just when I access one tab, sometimes when switching between tabs.

**To Reproduce**
Tab Wrangler Settings:
Close Inactive Tabs after 1440 minutes
Auto-close tabs only if I have more than 20 tabs open
Remember up to 200 closed tabs
Reset a tab's timer only after it is active for 1 second
Don't close tabs that are playing audio
Prevent duplicate tabs in the tab corral: if URL matches exactly

1. open the tab wrangler extension
2. select the tab lock tab
3. sort by Time until close (descending)
4. Scroll down the list and find a tab that is in a window with multiple other tabs where all tabs have a "noticeably" smaller time to close than the maximum of 1440 minutes
5. Select one of those tabs in the Chrome Window
6. Return to the Tab Wrangler Tab Lock Tab, and observe that all of the tabs in the Chrome Window had their timers reset, not just the tab you selected.

**Expected behavior**
ONLY the accessed tab should reset its timer to 1440 minutes, and not all of the other tabs in the Chrome window

**Version (please complete the following information):**
 - OS: MacOS Monterey v12.1
 - Browser Chrome
 - Version 97.0.4692.99 (x86_64)
 - Google Chrome is signed in with a username managed by a company (ie not a free Google ID)

**Comment by nol166** [comment] 2022-03-16 15:51
Same issue here. It seems like they are all delegated to the same `setTimeout()` or something

**Comment by reynoldscem** [comment] 2022-04-20 08:41
It seems this way for me too in firefox

**Comment by jimmylad** [comment] 2022-08-08 07:13
Same here on Mac Chrome

**Comment by ssorallen** [comment] 2022-12-02 20:44
Do you have more than the minimum (20 in your case) tabs open?

The logic as it is now intentionally resets the timer of all tabs when there are fewer than the minimum open, and this is so that tabs do not immediately close as soon as you open a new tab:

https://github.com/tabwrangler/tabwrangler/blob/master/app/background.ts#L43-L53

**Comment by nol166** [comment] 2022-12-02 20:50
Sweet! I will check it out. Thank you

**Comment by ssorallen** [comment] 2024-12-29 20:38
Closing as "can't reproduce" - this looks like fewer than the minimum number of tabs were open.

**Closed by ssorallen** 2024-12-29 20:38 UTC
