### ISSUE TITLE
Restoring tab order

### ISSUE THREAD

**Issue by pruchkin2** [tabwrangler/tabwrangler#124] opened 2017-04-10 13:59 UTC
Wish it would put them back in the same tab order - is that possible?

**Comment by pruchkin2** [comment] 2017-04-10 18:08
on a related note, if one has multiple windows open w/ different tabs in each,  wrangle the tabs, then when reopening it opens all wrangles tabs in both windows, which makes no sense

**Comment by ssorallen** [comment] 2017-04-30 00:11
RE: tab order

The [`chrome.tabs.query` API](https://developer.chrome.com/extensions/tabs#method-query) does return an index for each tab, but it's only relevant to the current open tabs. If the tab was closed yesterday, and the tabs you're looking at now are significantly different, does it matter that the tab was at the beginning of the list yesterday? Would you find this valuable? It's certainly possible to add.

**Comment by ssorallen** [comment] 2017-04-30 00:13
RE: re-opening tabs

Can you explain how this happened for you? I can't reproduce the issue of opening the same tabs in multiple windows. Can you give me steps to do that?

**Comment by ssorallen** [comment] 2018-03-06 02:59
This was partially solved by #125. If the tab's session is still recoverable, the tab will be restored it its original index and window.

**Comment by KTamas** [comment] 2021-12-11 12:16
i don't think any further enhancements can be made here, so closing this.

**Closed by KTamas** 2021-12-11 12:16 UTC
Labels: enhancement
